apiVersion: example.org/v1alpha1
kind: awsbuildprojectclaim
metadata:
  name: my-codebuild-project
spec:
  base_capacity: "1"
  compute_fleet_type: "BUILD_GENERAL1_SMALL"
  enviroment_type: "LINUX_CONTAINER"
  fleet_name: "teste_deivid"
  overflow_behavior: "QUEUE"
  project_service_role: "arn:aws:iam::907680593597:role/crossplane-iam-role-my-iamrole-s3-claim-jmlt7-dws7z"
  max_capacity: "2"
  projectName: "teste-codebuild"
  service_role: "arn:aws:iam::907680593597:role/crossplane-iam-role-my-iamrole-s3-claim-jmlt7-dws7z"
  compute_type: "BUILD_GENERAL1_SMALL"
  source_location: "https://github.com/deivid-andrade/crossplane-lab"
