apiVersion: example.org/v1alpha1
kind: awsbuildprojectclaim
metadata:
  name: my-codebuild-project
spec:
  parameters:
    base_capacity: "1"
    compute_fleet_type: "BUILD_GENERAL1_SMALL"
    enviroment_type: "LINUX_CONTAINER"
    fleet_name: "teste_deivid122411199114622233222222222222111"
    overflow_behavior: "QUEUE"
    max_capacity: "2"
    projectName: "teste-codebuild"
    compute_type: "BUILD_GENERAL1_SMALL"
    source_location: "https://github.com/deivid-andrade/ansible-jfrog-remote"

