apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: awsbuildprojects.example.org
spec:
  group: example.org
  names:
    kind: awsbuildproject
    listKind: awsbuildprojectlist
    plural: awsbuildprojects
    singular: awsbuildproject
  claimNames:
    kind: awsbuildprojectclaim
    plural: awsbuildprojectclaims
    singular: awsbuildprojectclaim
  versions:
    - name: "v1alpha1"
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                role_arn:
                  type: string
                parameters:
                  type: object
                  description: "The parameters for the AWS CodeBuild Project."
                  properties:
                    base_capacity:
                      type: string
                    compute_fleet_type:
                      type: string
                    fleet_name:
                      type: string
                    overflow_behavior:
                      type: string
                    max_capacity:
                      type: string
                    projectName:
                      type: string
                    compute_type:
                      type: string
                    source_location:
                      type: string
                    enviroment_type:
                      type: string
            status:
              description: "Status of the AWS CodeBuild Project."
              properties:
                iam_role_arn:
                  type: string