apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: awsbuildprojects.example.org
spec:
  group: example.org
  names:
    kind: awsbuildproject
    listKind: awsbuildprojectlist
    plural: awsbuildprojects
    singular: awsbuildproject
  claimNames:
    kind: awsbuildprojectclaim
    plural: awsbuildprojectclaims
    singular: awsbuildprojectclaim
  versions:
    - name: "v1alpha1"
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                base_capacity:
                  type: string
                compute_fleet_type:
                  type: string
                fleet_name:
                  type: string
                overflow_behavior:
                  type: string
                project_service_role:
                  type: string
                max_capacity:
                  type: string
                projectName:
                  type: string
                service_role:
                  type: string
                compute_type:
                  type: string
                source_location:
                  type: string
                enviroment_type:
                  type: string
                token_github:
                  type: string