apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: awsbuildprojects.example.org
spec:
  group: example.org
  names:
    kind: awsbuildproject
    listKind: awsbuildprojectlist
    plural: awsbuildprojects
    singular: awsbuildproject
  claimNames:
    kind: awsbuildprojectclaim
    plural: awsbuildprojectclaims
    singular: awsbuildprojectclaim
  versions:
    - name: "v1alpha1"
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectName:
                  type: string
                environmentType:
                  type: string
                sourceLocation:
                  type: string
                serviceRole:
                  type: string
