---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-eu-west-1
spec:
  credentials:
  - filename: aws-creds.ini
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
  configuration: |
      terraform {
        required_providers {
          aws = {
            source = "hashicorp/aws"
            version = "5.6.1"
          }
        }
        backend "kubernetes" {
          secret_suffix     = "providerconfig-aws-eu-west-1"
          namespace         = "crossplane-system"
          in_cluster_config = true
        }
      }
      provider "aws" {
        shared_credentials_files = ["${path.module}/aws-creds.ini"]
        region = "us-east-1"
      }