apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-eu-west-2-aws-codebuild
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds