apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: iamrole-composition
spec:
  compositeTypeRef:
    apiVersion: aws.example.org/v1alpha1
    kind: XIARMRole  # Assumindo o nome do tipo de recurso composite
  resources:
    - name: terraform-iam-role
      base:
        apiVersion: tf.upbound.io/v1beta1
        kind: Workspace
        spec:
          providerConfigRef:
            name: aws-eu-west-1  # Configuração do provedor AWS
          forProvider:
            source: Inline
            module: |
              resource "aws_iam_role" "example_role" {
                name               = "crossplane-iam-role-${terraform.workspace}"
                assume_role_policy = jsonencode({
                  Version = "2012-10-17"
                  Statement = [
                    {
                      Effect    = "Allow"
                      Principal = {
                        Service = "codebuild.amazonaws.com"
                      }
                      Action    = "sts:AssumeRole"
                    }
                  ]
                })
              }

              resource "aws_iam_policy" "codebuild_policy" {
                name        = "codebuild-full-access-policy"
                description = "Policy to allow full access for CodeBuild, S3, ECR, and CloudWatch"
                policy      = jsonencode({
                  Version = "2012-10-17"
                  Statement = [
                    {
                      Effect   = "Allow"
                      Action   = ["s3:*"]
                      Resource = "*"
                    },
                    {
                      Effect   = "Allow"
                      Action   = ["logs:*"]
                      Resource = "*"
                    },
                    {
                      Effect   = "Allow"
                      Action   = ["ecr:*"]
                      Resource = "*"
                    },
                    {
                      Effect   = "Allow"
                      Action   = ["codebuild:*"]
                      Resource = "*"
                    }
                  ]
                })
              }

              resource "aws_iam_role_policy_attachment" "example_attachment" {
                policy_arn = aws_iam_policy.codebuild_policy.arn
                role       = aws_iam_role.example_role.name
              }

              output "role_name" {
                value = aws_iam_role.example_role.name
              }
          writeConnectionSecretToRef:
            namespace: default
            name: terraform-workspace-iamrole
